import { useState,useEffect,useRef } from 'react';
import { useParams,Link,useNavigate } from 'react-router-dom';
import TalkingAvatar from '../components/TalkingAvatar.jsx';
import { getUtente } from '../data/utenteCorrente.js';
const COLORI_AVATAR={'Ada Lovelace':'#8C82E8','Marie Curie':'#F49A86','Margherita Hack':'#71C9C2','Samantha Cristoforetti':'#E7B85B'};
function Chat(){const {avatarId}=useParams();const navigate=useNavigate();const avatarRef=useRef(null);const fineMessaggiRef=useRef(null);const [utente]=useState(()=>getUtente());const [avatar,setAvatar]=useState(null);const [messaggi,setMessaggi]=useState([]);const [testoInput,setTestoInput]=useState('');const [inviando,setInviando]=useState(false);const [conversationId,setConversationId]=useState(null);const [avatarStaParlando,setAvatarStaParlando]=useState(false);const [caricandoCronologia,setCaricandoCronologia]=useState(true);
useEffect(()=>{fetch('/api/avatars').then(r=>r.json()).then(lista=>setAvatar(lista.find(a=>String(a.id)===String(avatarId))||null)).catch(console.error)},[avatarId]);
useEffect(()=>{if(!utente){setCaricandoCronologia(false);return}fetch(`/api/chat/esistente/${utente.id}/${avatarId}`).then(r=>r.json()).then(d=>{if(d.conversation_id){setConversationId(d.conversation_id);setMessaggi(d.messaggi.map(m=>({mittente:m.mittente,contenuto:m.contenuto})))}}).catch(console.error).finally(()=>setCaricandoCronologia(false))},[utente,avatarId]);
useEffect(()=>{fineMessaggiRef.current?.scrollIntoView({behavior:'smooth'})},[messaggi]);useEffect(()=>()=>avatarRef.current?.ferma?.(),[]);
const inviaMessaggio=async e=>{e.preventDefault();const testo=testoInput.trim();if(!testo||inviando||!utente)return;avatarRef.current?.ferma?.();setMessaggi(p=>[...p,{mittente:'utente',contenuto:testo}]);setTestoInput('');setInviando(true);try{const risposta=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:utente.id,avatar_id:Number(avatarId),messaggio:testo,conversation_id:conversationId})});const dati=await risposta.json();if(!risposta.ok)throw new Error(dati.errore||'Errore sconosciuto');setConversationId(dati.conversation_id);setMessaggi(p=>[...p,{mittente:'avatar',contenuto:dati.risposta}]);avatarRef.current?.parla(dati.risposta)}catch(err){console.error(err);setMessaggi(p=>[...p,{mittente:'avatar',contenuto:"Mi dispiace, c'è stato un problema. Riprova tra poco."}])}finally{setInviando(false)}};
if(!utente)return <div className="simple-state"><h1>Crea prima il tuo profilo</h1><p>Così possiamo personalizzare le risposte per te.</p><button className="button-primary" onClick={()=>navigate('/registrati',{state:{da:`/chat/${avatarId}`}})}>Crea il tuo profilo</button></div>;
if(!avatar||caricandoCronologia)return <div className="simple-state"><p>Caricamento...</p></div>;
const colore=COLORI_AVATAR[avatar.nome]||'#8C82E8';const nomeBreve=avatar.nome.split(' ')[0];return <div className="chat-page-large" style={{'--avatar-color':colore}}><Link to="/avatar" className="chat-back-link">← Tutte le mentor</Link><div className="chat-layout"><aside className="chat-avatar-panel"><div className="chat-avatar-title"><span className="eyebrow">LA TUA MENTOR</span><h1>{avatar.nome}</h1><p style={{color:colore}}>{avatar.disciplina}</p></div><div className="chat-avatar-stage"><TalkingAvatar nome={avatar.nome} variant="chat" width="100%" height={540} ref={avatarRef} onStateChange={setAvatarStaParlando}/></div><div className="chat-avatar-ready"><span className="chat-avatar-ready-dot"/><div><strong>{avatarStaParlando?`${nomeBreve} sta parlando`:`Parla con ${nomeBreve}`}</strong><small>{avatarStaParlando?'Ascolta la sua risposta':'Falle una domanda quando vuoi'}</small></div></div>{avatarStaParlando&&<button type="button" className="chat-stop-button" onClick={()=>avatarRef.current?.ferma()}>Interrompi voce</button>}</aside><section className="chat-conversation-panel"><header className="chat-conversation-header"><span className="eyebrow">CONVERSAZIONE</span><h2>Chiedi quello che vuoi</h2><p>Nessuna domanda è troppo semplice.</p></header><div className="chat-messages">{messaggi.length===0&&<div className="chat-empty"><h3>Da dove vuoi iniziare?</h3><p>Puoi chiederle della sua storia, degli studi o del suo lavoro.</p></div>}{messaggi.map((m,i)=><div key={i} className={`chat-bubble ${m.mittente==='utente'?'chat-bubble-utente':'chat-bubble-avatar'}`}>{m.contenuto}</div>)}{inviando&&<div className="chat-bubble chat-bubble-avatar"><em>{nomeBreve} sta pensando...</em></div>}<div ref={fineMessaggiRef}/></div><form className="chat-input-bar" onSubmit={inviaMessaggio}><input type="text" value={testoInput} onChange={e=>setTestoInput(e.target.value)} placeholder={`Scrivi a ${nomeBreve}...`} disabled={inviando}/><button type="submit" className="button-primary" disabled={inviando||!testoInput.trim()}>Invia</button></form></section></div></div>}
export default Chat;
